# Generated by Django 2.2.13 on 2020-11-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20201111_2235"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scheduleview",
            old_name="field_id",
            new_name="fieldvalue_id",
        ),
    ]
