# Generated by Django 2.2.13 on 2020-11-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20201112_1301"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
