# Generated by Django 2.2.13 on 2020-11-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_field_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
