# Generated by Django 2.2.13 on 2020-11-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20201112_1444"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="scheduleview",
            index=models.Index(
                fields=["trigger_id"], name="core_schedu_trigger_7d0332_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleview",
            index=models.Index(
                fields=["fieldvalue_id"], name="core_schedu_fieldva_37fb16_idx"
            ),
        ),
    ]
